### ISSUE TITLE
Vulnerability view enhancement

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1286]
![Screenshot from 2023-08-30 18-53-16](https://github.com/nexB/vulnerablecode/assets/34160672/7545f12d-df18-434f-a30f-8471856fc604)
```... see Fixed by packages tab for more```

and

```... see Affected packages tab for more```

should be clickable links that moves to the tab when clicked.

**Comment by johnmhoran** [comment]
@TG1999 Note that this work also implicates the discussion we had several weeks ago in the weekly jit.si meeting that resulted in a request that the `Fixed by packages` tab and the `Affected packages` tab be consildated into a single tab with a table in which the rows contain relevant pairing of affected and fixed packages.  

I've just checked the recent issues and do not see an issue covering the tab-consolidation work so I'll add one shortly.  And we'll need to decide on the priority between this current issue 1286 and that tab-consolidation issue.

**Comment by johnmhoran** [comment]
Completed with this merged PR: https://github.com/nexB/vulnerablecode/pull/1288.
