### ISSUE TITLE
Duplicates in api response after every data dump

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#156]
After first import
```
(venv) shivam@shivam:~/coding/opensource/vulnerablecode$ curl http://127.0.0.1:8000/api/packages/?name=python-django
{"count":2 ..............
```

After second import
```
(venv) shivam@shivam:~/coding/opensource/vulnerablecode$ curl http://127.0.0.1:8000/api/packages/?name=python-django
{"count":4...............
```
This is critical. We probably need to enforce more constraints on our models.

**Comment by haikoschol** [comment]
Looks like a duplicate of https://github.com/nexB/vulnerablecode/issues/28, but I haven't dug into either one in detail to understand whether there are differences. In general our import process produces lots of duplicate rows which needs to be fixed. I hope to achieve that in one central place (instead of writing code to fill the DB in every importer) in #152.

**Comment by sbs2001** [comment]
Duplicate of #28
