### ISSUE TITLE
Revisit using migrations for initial data seeds

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#208]
There are possible issues with using migrations to add new data, such as if we want to squash migrations in the future and tying the addition of data to a historical model version of when they were added. It could be simpler to reconsider using migration and have a different seeding model like a class yielding some value, etc. That would be more flexible too IMHO.

**Comment by haikoschol** [comment]
The Django docs describe how to provide initial data here: https://docs.djangoproject.com/en/3.0/howto/initial-data/

The alternative to data migrations described on that page is using fixtures. I don't remember why I went with migrations instead of fixtures. Probably because writing Python is less annoying than JSON. Or because data migrations are included when the user runs `./manage.py migrate` and fixtures require an additional command (which is easy enough to mention in the docs).

**Comment by sbs2001** [comment]
@pombredanne , can you please suggest other concrete alternatives. As @haikoschol suggested  we can use fixtures , but is that going solve the problem? In fact I still don't understand the problem.
