### ISSUE TITLE
Run error after pull latest, "ModuleNotFoundError: No module named 'drf_spectacular'".

### ISSUE THREAD

**Issue by uboznikov** [nexB/vulnerablecode#312]
Hello,

I pulled latest and ran with Docker Compose, getting the error below:

![image](https://user-images.githubusercontent.com/16329085/105141537-43de4800-5b34-11eb-8b00-0ff9c92c9328.png)

**Comment by sbs2001** [comment]
@uboznikov  I just did a fresh docker-compose setup to reproduce the error, but didn't  encounter anything. 

Recently the project switched from `drf-yasg` to `drf-spectacular` for api doc generation. So a stale docker image might be the issue here ? 

Could you try deleting the docker image and retry fresh ?

**Comment by uboznikov** [comment]
@sbs2001 That solves it, thanks.

> Could you try deleting the docker image and retry fresh ?

Perhaps this could be added in the doc?

**Comment by sbs2001** [comment]
This is kind of rare case where the image was built, and then upstream had dependency changes. A small note about this makes sense :)

**Comment by pombredanne** [comment]
There must be a better way than deleting the image

**Comment by sbs2001** [comment]
@pombredanne  a better way would be to do 
```
sudo docker-compose up
sudo docker-compose exec web bash
pip install -r requirements.txt
```

**Comment by Pushpit07** [comment]
#427 closes this issue
