### ISSUE TITLE
Update deps  and their structure

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#348]
We are using pretty outdated deps. These should be upgraded, after all we don't want to be "vulnerable" . 

Unrelated: have requirement file separate dev dependencies.

**Comment by sbs2001** [comment]
@rolfschr  heads up ! Btw the nix tests are failing at https://github.com/nexB/vulnerablecode/pull/347 due to update in  deps

**Comment by Hritik14** [comment]
Repaste from #379 
>The pytest bug is weird. @Hritik14 could you try updating the venv pytest to latest and try running python -m pytest . Just to determine if issue is caused due to system pytest invocation or just some version incompability.

@sbs2001 I think you're right. It is failing because the tests are only compatible with pytest version shipped with the project requirements. 
Here is an asciinema reproducing my results:
[![asciicast](https://asciinema.org/a/WhwxQT9ANJQtvOo976mnqws6z.svg)](https://asciinema.org/a/WhwxQT9ANJQtvOo976mnqws6z)

As you can see, after first installation, `which pytest` points to the system pytest.
I have `pytest 6.2.2` installed and the project requires `pytest==5.3.2`.    
So, it is both due to system pytest invocation and version incompatibility.

Maybe we can look into this here

**Comment by prathamaror** [comment]
I have a pretty good idea about this should I start working on this I have some questions prior

**Comment by Hritik14** [comment]
This has been fixed by https://github.com/nexB/vulnerablecode/pull/379
