### ISSUE TITLE
Wrong key error when importing data from debian (using Docker while setup)

### ISSUE THREAD

**Issue by Pushpit07** [nexB/vulnerablecode#383]
I was setting up vulnerablecode using docker on macOS Big Sur. I ran `DJANGO_DEV=1 python manage.py import --all` to run all data importers as specified in the README and ran into this error-

File "/usr/local/lib/python3.8/site-packages/schema.py", line 396, in validate
        &nbsp;&nbsp;&nbsp;&nbsp;nvalue = Schema(svalue, error=e, ignore_extra_keys=i).validate(value)
  File "/usr/local/lib/python3.8/site-packages/schema.py", line 417, in validate
        &nbsp;&nbsp;&nbsp;&nbsp;raise SchemaWrongKeyError(message, e.format(data) if e else None)
schema.SchemaWrongKeyError: Wrong key 'bullseye-security' in {'bullseye': '1.17.0+ds1-1.3', 'bullseye-security': '1.17.0+ds1-1.3~deb11u1'}

<img width="1440" alt="Screenshot 2021-03-18 at 09 50 38" src="https://user-images.githubusercontent.com/57194612/111572971-a0c24b80-87cf-11eb-9800-27968c7a9868.png">
<img width="1440" alt="Screenshot 2021-03-18 at 09 50 44" src="https://user-images.githubusercontent.com/57194612/111572967-9f911e80-87cf-11eb-9ee7-97e1baa6f9f1.png">
<img width="1440" alt="Screenshot 2021-03-18 at 09 50 49" src="https://user-images.githubusercontent.com/57194612/111572953-999b3d80-87cf-11eb-8779-62599bb05943.png">

**Comment by sbs2001** [comment]
@Pushpit07  this is a known bug I have https://github.com/nexB/vulnerablecode/pull/378 which fixes this. Will merge that once I narrow down what's causing failure in the redhat importer. 

Atm that PR 's branch can run all importers except `redhat`

**Comment by sbs2001** [comment]
You could help in fixing the `redhat` importer btw, I'm occupied with another ticket atm. 

From the logs at https://pipelines.actions.githubusercontent.com/Ep9prel8NYELDl3abhBbfgiORCbX0JuViN8i8esKzVS8DdQt5i/_apis/pipelines/1/runs/130/signedlogcontent/3?urlExpires=2021-03-18T04%3A34%3A23.9071130Z&urlSigningMethod=HMACV1&urlSignature=sJLXLRjUZZiPl5J24k1eE1Ljte7e79N3jahByMOwWS8%3D

The issue seems to be at https://github.com/nexB/vulnerablecode/blob/8094f6e5fcea1023d50c29ae1ae01e291321974f/vulnerabilities/importers/redhat.py#L94 , caused due to absence of key "bugs"

**Comment by sbs2001** [comment]
FYI https://github.com/nexB/vulnerablecode/issues/384

**Comment by Pushpit07** [comment]
I've fixed #380. Have a look at that

**Comment by sbs2001** [comment]
Fixed via https://github.com/nexB/vulnerablecode/pull/378
