### ISSUE TITLE
Investigate and fix redhat import failure

### ISSUE THREAD

**Issue by sbs2001** [nexB/vulnerablecode#398]
The redhat importer is still failing after the fix at https://github.com/nexB/vulnerablecode/pull/387. 

From  the logs at https://pipelines.actions.githubusercontent.com/Ep9prel8NYELDl3abhBbfgiORCbX0JuViN8i8esKzVS8DdQt5i/_apis/pipelines/1/runs/151/signedlogcontent/3?urlExpires=2021-03-24T04%3A20%3A33.2100559Z&urlSigningMethod=HMACV1&urlSignature=7VXaMaJelaCEUG6EDzDbZKLAw%2BfWbGUypuHe164RCjE%3D

It seems there is problem at https://github.com/nexB/vulnerablecode/blob/bfa005ece230ada9032c3c0b4a7bab7b59673e0b/vulnerabilities/importers/redhat.py#L93. 

To fix this:

1.Find the cause of 443 
2.Add a workaround on non-json response .

**Comment by Hritik14** [comment]
I'm working on it

**Comment by Hritik14** [comment]
Update: I ran the importer for 6 hours straight and it wasn't responding after the fetching.
Either the amount of advisories is so high that it's taking lot of time to actually import   (https://github.com/nexB/vulnerablecode/issues/210) or it's something else.

I'll investigate further by Monday.

**Comment by Hritik14** [comment]
Update: The root cause is abusing the server with so many requests in such a short time. The server is replying with `502: Proxy Error` and sometimes with `104: Connection reset`. I'm implementing a requests helper to retry with sane back-offs on such situations.
I've also mailed bugzilla-owner@redhat.com to ask if there exists any scraping restrictions in a given time.

**Comment by Hritik14** [comment]
Update: Today I woke up to this and I'm happy :D 
![image](https://user-images.githubusercontent.com/7457065/113282038-07815200-9304-11eb-8ba8-0fa2215aef4d.png)
