### ISSUE TITLE
Scrape Debian security advisories

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#6]
The goal is to collect and store these in our models

**Comment by tdruez** [comment]
From https://github.com/nexB/vulnerablecode/pull/14#issuecomment-315236716

@kartiksibal the current data structure for the returned CVEs is not easily usable, instead of the current 3 lists of strings, we should return a single list of CVEs dictionaries.

Instead of:
```
(
    ['CVE-2016-5416', 'CVE-2012-6655'],  
    ['389-ds-base', 'accountsservice'],  
    ['not yet assigned', 'not yet assigned'],
)
```

Return:
```
[
    {
        'cve_id': 'CVE-2016-5416', 
        'package_name': '389-ds-base', 
        'vulnerability_status': 'not yet assigned',
    },
    {
        'cve_id': 'CVE-2012-6655', 
        'package_name': 'accountsservice', 
        'vulnerability_status': 'not yet assigned',
    },
]
```
It will be much easier to use that data structure to then create model instances (save the data in the DB).
