### ISSUE TITLE
Update VCIO Landing Page

### ISSUE THREAD

**Issue by pombredanne** [nexB/vulnerablecode#798]
See also #772

**Comment by mjherzog** [comment]
Update the VCIO landing page to emulate the look and feel of SCIO. Some key points are:
- Narrow the page “width” to emulate the SCIO landing page
- Change the page “header” to emulate the SCIO page header with the items:
  - VulnerableCode.io
   - Packages
   - Vulnerabilities
   - API Documentation (we do not have the same API access as with SCIO)
   - Version (this will need to be the version of VulnerableCode - we can document that on hover)
- Keep the page footer (we are missing a footer on the SCIO landing page - it should have one)
- Show two search sections SCIO style
   - Packages
   - Vulnerabilities
   There is no data to display here as we have for Projects because the only VCIO functionality is to search for a specific Package or Vulnerability.
   - We should display a block of simple help text under each Search box that tells you what to do/expect - 
     - For Packages we might say: “Search for currently known Vulnerabilities for a Package-URL or a Package name.”
     - For Vulnerabilities we might say: “Search for complete information for a VULCOID (VulnerableCode Database ID).”
- Bonus item - add a simple favicon. Just the letters “VC” with a light blue background would suffice for now.

**Comment by pombredanne** [comment]
I think we should revisit the design for search to have a single search box rather than to have multiple search boxes. The content that is searched can help determine easily what we are searching. For instance `CVE` prefix in the search would mean searching for vulnerabilities. Or a pkg prefix would mean this is a purl. Also in general we should be flexible in what we accept for search and not reject anything, possibly suggesting alternative searches like with a "did you mean?"

**Comment by mjherzog** [comment]
A wise man once told me to avoid premature optimization.

**Comment by johnmhoran** [comment]
I'm adding tasks beyond those initially identified above:
- [ ] Move landing page search instructions to icon-hover displays
- [ ] Add relevant search box/capability to the package/purl and vulnerability search results and details pages
- [ ] Add info to package/purl details page reflecting closest version with no unresolved reported vulnerabilities

(More to come.)

**Comment by johnmhoran** [comment]
This has been completed.
