### ISSUE TITLE
Bad link in readthedocs

### ISSUE THREAD

**Issue by DennisClark** [nexB/vulnerablecode#885]
In https://vulnerablecode.readthedocs.io/en/latest/introduction.html#how-does-it-work  
there is this statement

These data sources (see complete list [here](https://vulnerablecode.readthedocs.io/en/latest/SOURCES.rst)) include 

but if you click on the link, you discover that the referenced page does not exist.

**Comment by DennisClark** [comment]
Assigning to @TG1999  but available to anyone who has access to an official list of data sources.

**Comment by johnmhoran** [comment]
@DennisClark @TG1999 I think I've located the missing `SOURCES.rst` file directly under the project/repo root rather than under `/docs` -- see https://github.com/nexB/vulnerablecode/blob/main/SOURCES.rst.  To be certain my "fix" (details below) is what we want, I'd like to show it to you via a huddle whenever it's convenient and make sure this now links to the data that we want to link to.  Please ping me whenever you'd like to see this.

We already incorporate this file, in its current location, in `vulnerablecode/docs/source/reference_importer_overview.rst` with the syntax `.. include:: ../../SOURCES.rst`.  Based on some googling, the problem with the missing link seems to be that because the file is outside of `/docs`, a link rather than an `include` does not work.

I've fixed this by creating a new `.rst` under `/docs` named `importers_link.rst` that contains an `include` to the `SOURCES.rst` file, a title, and an internal ref, like this:

```
.. _importers_link:

Importers
=========

.. include:: ../../SOURCES.rst
```

That's the entire file, and we link to it like this: 

```
These data sources (see complete list :ref:`here <importers_link>`) include security advisories published by Linux and BSD distributions . . . .
```

**Comment by DennisClark** [comment]
makes sense to me  --  thanks @johnmhoran

**Comment by johnmhoran** [comment]
Thanks @DennisClark .  @TG1999 If this looks good to you as well, please let me know and I'll close this as fixed.

**Comment by johnmhoran** [comment]
Done and closing.
