### ISSUE TITLE
UI bug in reference table

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#916]
![Screenshot from 2022-09-13 23-04-27](https://user-images.githubusercontent.com/34160672/189971397-e25bd641-361a-4b52-bbcc-d11760118286.png)

**Comment by johnmhoran** [comment]
@TG1999 Probably because my local DB contains a small subset of the data, I'm not seeing this exact issue, but I am seeing an unwanted expansion of the column, e.g., 
![image](https://user-images.githubusercontent.com/11096678/189976880-074adcf6-9c6c-47c9-89f9-3eba25612176.png)

Am I correct in thinking that we simply want a reasonable wrap applied to the URL column in the References tab?  E.g.,

![image](https://user-images.githubusercontent.com/11096678/189978194-8c8c2a88-9615-47d0-8925-8936834f9e1a.png)

**Comment by TG1999** [comment]
@johnmhoran I think this will be helpful can you change the data in the rows once with some big reference_ids and urls (like CPEs) and then try this out once?

**Comment by johnmhoran** [comment]
@TG1999 I already searched for `cpe` but only 2 hits and neither has both a long Reference id and a long URL like your example.

**Comment by johnmhoran** [comment]
@TG1999 and I manipulated the UI data plus my new class and got this result:

![image](https://user-images.githubusercontent.com/11096678/189982940-1517d297-bc73-452e-b9de-ce7fba53c2cf.png)

**Comment by TG1999** [comment]
closed by https://github.com/nexB/vulnerablecode/pull/919 thanks @johnmhoran
